/*
 * Loading Optimization
 *
 * With the Bin Packing service you can pack a number of items of various types into a number of bins of various types.
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.binpacking.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.binpacking.Model
{
    /// <summary>
    /// Describes the surface loads in [g/cm²] on an item acting on each of its axis. If an axis is not provided it is assumed to be irrelevant and/or non-restrictive. 
    /// </summary>
    [DataContract(Name = "ItemSurfaceLoads")]
    public partial class ItemSurfaceLoads : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemSurfaceLoads" /> class.
        /// </summary>
        /// <param name="x">Surface load acting on the x-axis (width) of the item in [g/cm²]..</param>
        /// <param name="y">Surface load acting on the y-axis (height) of the item in [g/cm²]..</param>
        /// <param name="z">Surface load acting on the z-axis (length) of the item in [g/cm²]..</param>
        public ItemSurfaceLoads(double? x = default(double?), double? y = default(double?), double? z = default(double?))
        {
            this.X = x;
            this.Y = y;
            this.Z = z;
        }

        /// <summary>
        /// Surface load acting on the x-axis (width) of the item in [g/cm²].
        /// </summary>
        /// <value>Surface load acting on the x-axis (width) of the item in [g/cm²].</value>
        [DataMember(Name = "x", EmitDefaultValue = true)]
        public double? X { get; set; }

        /// <summary>
        /// Surface load acting on the y-axis (height) of the item in [g/cm²].
        /// </summary>
        /// <value>Surface load acting on the y-axis (height) of the item in [g/cm²].</value>
        [DataMember(Name = "y", EmitDefaultValue = true)]
        public double? Y { get; set; }

        /// <summary>
        /// Surface load acting on the z-axis (length) of the item in [g/cm²].
        /// </summary>
        /// <value>Surface load acting on the z-axis (length) of the item in [g/cm²].</value>
        [DataMember(Name = "z", EmitDefaultValue = true)]
        public double? Z { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ItemSurfaceLoads {\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Z: ").Append(Z).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // X (double?) maximum
            if (this.X > (double?)80000000)
            {
                yield return new ValidationResult("Invalid value for X, must be a value less than or equal to 80000000.", new [] { "X" });
            }

            // X (double?) minimum
            if (this.X < (double?)0)
            {
                yield return new ValidationResult("Invalid value for X, must be a value greater than or equal to 0.", new [] { "X" });
            }

            // Y (double?) maximum
            if (this.Y > (double?)80000000)
            {
                yield return new ValidationResult("Invalid value for Y, must be a value less than or equal to 80000000.", new [] { "Y" });
            }

            // Y (double?) minimum
            if (this.Y < (double?)0)
            {
                yield return new ValidationResult("Invalid value for Y, must be a value greater than or equal to 0.", new [] { "Y" });
            }

            // Z (double?) maximum
            if (this.Z > (double?)80000000)
            {
                yield return new ValidationResult("Invalid value for Z, must be a value less than or equal to 80000000.", new [] { "Z" });
            }

            // Z (double?) minimum
            if (this.Z < (double?)0)
            {
                yield return new ValidationResult("Invalid value for Z, must be a value greater than or equal to 0.", new [] { "Z" });
            }

            yield break;
        }
    }

}
