/*
 * Loading Optimization
 * With the Bin Packing service you can pack a number of items of various types into a number of bins of various types.
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.binpacking.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import io.swagger.annotations.ApiModel;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Algorithmic focus for the bin packing operation: * &#x60;BUILD_LAYERS&#x60; - Focus on building horizontal layers of similar items. This will freely use available floor space with no special regard to loading meters. * &#x60;REDUCE_LOADING_METERS&#x60; - Focus on reducing loading meters. This might result in less efficient use of overall volume.
 */
public enum BinPackingFocus {
  
  BUILD_LAYERS("BUILD_LAYERS"),
  
  REDUCE_LOADING_METERS("REDUCE_LOADING_METERS");

  private String value;

  BinPackingFocus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BinPackingFocus fromValue(String value) {
    for (BinPackingFocus b : BinPackingFocus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

