/*
 * Loading Optimization
 * With the Bin Packing service you can pack a number of items of various types into a number of bins of various types.
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.binpacking.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.binpacking.model.ItemNotPacked;
import com.ptvgroup.developer.client.binpacking.model.PackedBin;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.ptvgroup.developer.client.binpacking.ApiClient;
/**
 * Describes a packing solution.
 */
@JsonPropertyOrder({
  PackBinsResponse.JSON_PROPERTY_PACKED_BINS,
  PackBinsResponse.JSON_PROPERTY_ITEMS_NOT_PACKED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-28T13:28:30.257776203Z[Etc/UTC]", comments = "Generator version: 7.8.0")
public class PackBinsResponse {
  public static final String JSON_PROPERTY_PACKED_BINS = "packedBins";
  private List<PackedBin> packedBins = new ArrayList<>();

  public static final String JSON_PROPERTY_ITEMS_NOT_PACKED = "itemsNotPacked";
  private List<ItemNotPacked> itemsNotPacked = new ArrayList<>();

  public PackBinsResponse() { 
  }

  public PackBinsResponse packedBins(List<PackedBin> packedBins) {
    this.packedBins = packedBins;
    return this;
  }

  public PackBinsResponse addPackedBinsItem(PackedBin packedBinsItem) {
    if (this.packedBins == null) {
      this.packedBins = new ArrayList<>();
    }
    this.packedBins.add(packedBinsItem);
    return this;
  }

  /**
   * List with one entry for each bin that was used for packing items in this solution.
   * @return packedBins
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PACKED_BINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<PackedBin> getPackedBins() {
    return packedBins;
  }


  @JsonProperty(JSON_PROPERTY_PACKED_BINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackedBins(List<PackedBin> packedBins) {
    this.packedBins = packedBins;
  }


  public PackBinsResponse itemsNotPacked(List<ItemNotPacked> itemsNotPacked) {
    this.itemsNotPacked = itemsNotPacked;
    return this;
  }

  public PackBinsResponse addItemsNotPackedItem(ItemNotPacked itemsNotPackedItem) {
    if (this.itemsNotPacked == null) {
      this.itemsNotPacked = new ArrayList<>();
    }
    this.itemsNotPacked.add(itemsNotPackedItem);
    return this;
  }

  /**
   * List of items and its quantities, that could not be processed in this request. 
   * @return itemsNotPacked
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITEMS_NOT_PACKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ItemNotPacked> getItemsNotPacked() {
    return itemsNotPacked;
  }


  @JsonProperty(JSON_PROPERTY_ITEMS_NOT_PACKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItemsNotPacked(List<ItemNotPacked> itemsNotPacked) {
    this.itemsNotPacked = itemsNotPacked;
  }


  /**
   * Return true if this PackBinsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackBinsResponse packBinsResponse = (PackBinsResponse) o;
    return Objects.equals(this.packedBins, packBinsResponse.packedBins) &&
        Objects.equals(this.itemsNotPacked, packBinsResponse.itemsNotPacked);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packedBins, itemsNotPacked);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackBinsResponse {\n");
    sb.append("    packedBins: ").append(toIndentedString(packedBins)).append("\n");
    sb.append("    itemsNotPacked: ").append(toIndentedString(itemsNotPacked)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `packedBins` to the URL query string
    if (getPackedBins() != null) {
      for (int i = 0; i < getPackedBins().size(); i++) {
        if (getPackedBins().get(i) != null) {
          joiner.add(getPackedBins().get(i).toUrlQueryString(String.format("%spackedBins%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `itemsNotPacked` to the URL query string
    if (getItemsNotPacked() != null) {
      for (int i = 0; i < getItemsNotPacked().size(); i++) {
        if (getItemsNotPacked().get(i) != null) {
          joiner.add(getItemsNotPacked().get(i).toUrlQueryString(String.format("%sitemsNotPacked%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

