/* tslint:disable */
/* eslint-disable */
/**
 * Loading Optimization
 * With the Bin Packing service you can pack a number of items of various types into a number of bins of various types.
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Size of an item or bin.
 * @export
 * @interface BoxDimensions
 */
export interface BoxDimensions {
    /**
     * Extent along x-axis (width) in [cm].
     * @type {number}
     * @memberof BoxDimensions
     */
    x: number;
    /**
     * Extent along y-axis (height) in [cm].
     * @type {number}
     * @memberof BoxDimensions
     */
    y: number;
    /**
     * Extent along z-axis (length) in [cm].
     * @type {number}
     * @memberof BoxDimensions
     */
    z: number;
}

/**
 * Check if a given object implements the BoxDimensions interface.
 */
export function instanceOfBoxDimensions(value: object): value is BoxDimensions {
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    if (!('z' in value) || value['z'] === undefined) return false;
    return true;
}

export function BoxDimensionsFromJSON(json: any): BoxDimensions {
    return BoxDimensionsFromJSONTyped(json, false);
}

export function BoxDimensionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoxDimensions {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
        'z': json['z'],
    };
}

export function BoxDimensionsToJSON(value?: BoxDimensions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'x': value['x'],
        'y': value['y'],
        'z': value['z'],
    };
}

