/* tslint:disable */
/* eslint-disable */
/**
 * Loading Optimization
 * With the Bin Packing service you can pack a number of items of various types into a number of bins of various types.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The current status of the calculation.
 *  * `RUNNING` - The calculation is still running.
 *  * `SUCCEEDED` - The calculation has completed successfully. Now the response can be requested calling getPackedBins.
 *  * `FAILED` - The calculation has completed with a failure. More details can be requested calling getPackedBins.
 * @export
 * @enum {string}
 */
export enum CalculationStatus {
    RUNNING = 'RUNNING',
    SUCCEEDED = 'SUCCEEDED',
    FAILED = 'FAILED'
}

export function CalculationStatusFromJSON(json: any): CalculationStatus {
    return CalculationStatusFromJSONTyped(json, false);
}

export function CalculationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalculationStatus {
    return json as CalculationStatus;
}

export function CalculationStatusToJSON(value?: CalculationStatus | null): any {
    return value as any;
}

