/* tslint:disable */
/* eslint-disable */
/**
 * Loading Optimization
 * With the Bin Packing service you can pack a number of items of various types into a number of bins of various types.
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Describes the orientation that was used to place the item into the bin.
 * * `ORIGINAL` - Item was not re-oriented. Dimensions stay (x,y,z).
 * * `X` - Item was rotated around x-axis (widthwise) by +/-90 degrees compared to the original orientation. Dimensions are (x,z,y).
 * * `Y` - Item was rotated around y-axis (heightwise) by +/-90 degrees compared to the original orientation. Dimensions are (z,y,x).
 * * `Z` - Item was rotated around z-axis (lengthwise) by +/-90 degrees compared to the original orientation. Dimensions are (y,x,z).
 * * `XZ` - Item was rotated around x- then z-axis (width- then heightwise) by +/-90 degrees compared to the original orientation. Dimensions are (z,x,y).
 * * `YZ` - Item was rotated around x- then z-axis (width- then heightwise) by +/-90 degrees compared to the original orientation. Dimensions are (z,x,y).
 * @export
 */
export const ItemOrientation = {
    ORIGINAL: 'ORIGINAL',
    X: 'X',
    Y: 'Y',
    Z: 'Z',
    XZ: 'XZ',
    YZ: 'YZ'
} as const;
export type ItemOrientation = typeof ItemOrientation[keyof typeof ItemOrientation];


export function ItemOrientationFromJSON(json: any): ItemOrientation {
    return ItemOrientationFromJSONTyped(json, false);
}

export function ItemOrientationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemOrientation {
    return json as ItemOrientation;
}

export function ItemOrientationToJSON(value?: ItemOrientation | null): any {
    return value as any;
}

