/* tslint:disable */
/* eslint-disable */
/**
 * Loading Optimization
 * With the Bin Packing service you can pack a number of items of various types into a number of bins of various types.
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines the number of instances of an item to unload.
 * @export
 * @interface ItemsToUnload
 */
export interface ItemsToUnload {
    /**
     * ID of the item.
     * @type {string}
     * @memberof ItemsToUnload
     */
    itemId: string;
    /**
     * The amount of instances of the item to unload.
     * @type {number}
     * @memberof ItemsToUnload
     */
    numberOfInstances?: number;
}

/**
 * Check if a given object implements the ItemsToUnload interface.
 */
export function instanceOfItemsToUnload(value: object): value is ItemsToUnload {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    return true;
}

export function ItemsToUnloadFromJSON(json: any): ItemsToUnload {
    return ItemsToUnloadFromJSONTyped(json, false);
}

export function ItemsToUnloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemsToUnload {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'],
        'numberOfInstances': json['numberOfInstances'] == null ? undefined : json['numberOfInstances'],
    };
}

export function ItemsToUnloadToJSON(value?: ItemsToUnload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'itemId': value['itemId'],
        'numberOfInstances': value['numberOfInstances'],
    };
}

