/* tslint:disable */
/* eslint-disable */
/**
 * Loading Optimization
 * With the Bin Packing service you can pack a number of items of various types into a number of bins of various types.
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemNotPacked } from './ItemNotPacked';
import {
    ItemNotPackedFromJSON,
    ItemNotPackedFromJSONTyped,
    ItemNotPackedToJSON,
} from './ItemNotPacked';
import type { PackedBin } from './PackedBin';
import {
    PackedBinFromJSON,
    PackedBinFromJSONTyped,
    PackedBinToJSON,
} from './PackedBin';

/**
 * Describes a packing solution.
 * @export
 * @interface PackBinsResponse
 */
export interface PackBinsResponse {
    /**
     * List with one entry for each bin that was used for packing items in this solution.
     * @type {Array<PackedBin>}
     * @memberof PackBinsResponse
     */
    packedBins?: Array<PackedBin>;
    /**
     * List of items and its quantities, that could not be processed in this request.
     * 
     * @type {Array<ItemNotPacked>}
     * @memberof PackBinsResponse
     */
    itemsNotPacked?: Array<ItemNotPacked>;
}

/**
 * Check if a given object implements the PackBinsResponse interface.
 */
export function instanceOfPackBinsResponse(value: object): value is PackBinsResponse {
    return true;
}

export function PackBinsResponseFromJSON(json: any): PackBinsResponse {
    return PackBinsResponseFromJSONTyped(json, false);
}

export function PackBinsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackBinsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'packedBins': json['packedBins'] == null ? undefined : ((json['packedBins'] as Array<any>).map(PackedBinFromJSON)),
        'itemsNotPacked': json['itemsNotPacked'] == null ? undefined : ((json['itemsNotPacked'] as Array<any>).map(ItemNotPackedFromJSON)),
    };
}

export function PackBinsResponseToJSON(value?: PackBinsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'packedBins': value['packedBins'] == null ? undefined : ((value['packedBins'] as Array<any>).map(PackedBinToJSON)),
        'itemsNotPacked': value['itemsNotPacked'] == null ? undefined : ((value['itemsNotPacked'] as Array<any>).map(ItemNotPackedToJSON)),
    };
}

