/* tslint:disable */
/* eslint-disable */
/**
 * Loading Optimization
 * With the Bin Packing service you can pack a number of items of various types into a number of bins of various types.
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PackedBinsIdentifier
 */
export interface PackedBinsIdentifier {
    /**
     * The ID of the packed bins.
     * @type {string}
     * @memberof PackedBinsIdentifier
     */
    id: string;
}

/**
 * Check if a given object implements the PackedBinsIdentifier interface.
 */
export function instanceOfPackedBinsIdentifier(value: object): value is PackedBinsIdentifier {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function PackedBinsIdentifierFromJSON(json: any): PackedBinsIdentifier {
    return PackedBinsIdentifierFromJSONTyped(json, false);
}

export function PackedBinsIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackedBinsIdentifier {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function PackedBinsIdentifierToJSON(value?: PackedBinsIdentifier | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

