/* tslint:disable */
/* eslint-disable */
/**
 * Loading Optimization
 * With the Bin Packing service you can pack a number of items of various types into a number of bins of various types.
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StackingRestrictionType } from './StackingRestrictionType';
import {
    StackingRestrictionTypeFromJSON,
    StackingRestrictionTypeFromJSONTyped,
    StackingRestrictionTypeToJSON,
} from './StackingRestrictionType';

/**
 * Define the stacking restriction for one item. Specifies which items are allowed or prohibited to be stacked on this item.
 * 
 * @export
 * @interface StackingRestrictions
 */
export interface StackingRestrictions {
    /**
     * ID of the item.
     * @type {string}
     * @memberof StackingRestrictions
     */
    itemId: string;
    /**
     * 
     * @type {StackingRestrictionType}
     * @memberof StackingRestrictions
     */
    restrictionType?: StackingRestrictionType;
    /**
     * Specifies the list of Item.id to which the restrictionType applies.
     * @type {Array<string>}
     * @memberof StackingRestrictions
     */
    itemIds?: Array<string>;
}



/**
 * Check if a given object implements the StackingRestrictions interface.
 */
export function instanceOfStackingRestrictions(value: object): value is StackingRestrictions {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    return true;
}

export function StackingRestrictionsFromJSON(json: any): StackingRestrictions {
    return StackingRestrictionsFromJSONTyped(json, false);
}

export function StackingRestrictionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StackingRestrictions {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'],
        'restrictionType': json['restrictionType'] == null ? undefined : StackingRestrictionTypeFromJSON(json['restrictionType']),
        'itemIds': json['itemIds'] == null ? undefined : json['itemIds'],
    };
}

export function StackingRestrictionsToJSON(value?: StackingRestrictions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'itemId': value['itemId'],
        'restrictionType': StackingRestrictionTypeToJSON(value['restrictionType']),
        'itemIds': value['itemIds'],
    };
}

